#!/bin/bash

echo "RSYNC --> Copy Windows"
osascript -e 'do shell script "rsync -avh --progress --exclude=sources/install.wim /Volumes/WIN/ /Volumes/WINUSB" ' cat > /Private/tmp/Win11-USB-Rsync.txt
Sleep 2
echo "Wimlib --> Split install.wim"
osascript -e 'do shell script "/usr/local/Cellar/wimlib/1.13.4/bin/wimlib-imagex split /Volumes/WIN/sources/install.wim /Volumes/WINUSB/sources/install.swm 4000" ' cat > /Private/tmp/Win11-USB-Wimlib.txt
rm -rf $HOME/Desktop/Win11-USB.txt
touch $HOME/Desktop/Win11-USB.txt

Sleep 2
cat /Private/tmp/Win11-USB-Rsync.txt /Private/tmp/Win11-USB-Wimlib.txt >> $HOME/Desktop/Win11-USB.txt
Sleep 1
rm -rf /Private/tmp/*.txt
echo "Done"


