#!/bin/bash
# script for install Wimlib on macOS
# chris1111 

echo "==============================================="
echo "Post Post-Install Script"
echo "==============================================="

#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
#echo "DEBUG: $ 4 = Root directory for the system: " $4

echo "preinstall: Path to installer....... $1"
echo "preinstall: Path to destination..... $2"
echo "preinstall: Path to dest volume..... $3"
echo "preinstall: Root of system folder... $4"


#############################################################################
ditto -x -k --sequesterRsrc --rsrc /Private/tmp/Cellar.zip /usr/local
Slepp 1
ditto -x -k --sequesterRsrc --rsrc /Private/tmp/lib.zip /usr/local
Sleep 1
ditto -x -k --sequesterRsrc --rsrc /Private/tmp/opt.zip /usr/local
Sleep 1
sudo chown -R root:wheel /usr/local/Cellar/
sudo chown -R root:wheel /usr/local/lib/
sudo chown -R root:wheel /usr/local/opt/

		